export const teamgallery = [
  {  
    preview: './images/footer/previewModal.png',
    original: './images/footer/SerhiiVoitsekhovskyi.jpg',
    username: 'Serhii Voitsekhovskyi',
    position: 'Team-lead/Developer',
    submitGit: 'https://github.com/svoits',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/AllaKaplia.jpg',
    username: 'Alla Kaplia',
    position: 'Scrum-master/Developer',
    submitGit: 'https://github.com/AllaKaplia',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/IlliaShulha.jpg',
    username: 'Illia Shulha',
    position: 'Developer',
    submitGit: 'https://github.com/cutestsun',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/OlenaKhomutovska.jpg',
    username: 'Olena Khomutovska',
    position: 'Developer',
    submitGit: 'https://github.com/Helen-A-lex',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/SkepskaKateryna.jpg',
    username: 'Skepska Kateryna',
    position: 'Developer',
    submitGit: 'https://github.com/wonderotter',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/YuriiRodenko.jpg',
    username: 'Yurii Rodenko',
    position: 'Developer',
    submitGit: 'https://github.com/YuriiRodenko',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/NatalyaSkyrda.jpg',
    username: 'Natalya Skyrda',
    position: 'Developer',
    submitGit: 'https://github.com/talask',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/previewModal.png',
    username: 'Artem',
    position: 'Developer',
    submitGit: 'https://github.com/ArtGer7',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/Mykola Ivanyshyn.jpg',
    username: 'Mykola Ivanyshyn',
    position: 'Developer',
    submitGit: 'https://github.com/Mikaeri',
  },
  {
    preview: './images/footer/previewModal.png',
    original: './images/footer/NataliaDemydenko.jpg',
    username: 'Natalia Demydenko',
    position: 'Developer',
    submitGit: 'https://github.com/Natalucia777',
    },
];