import './js/theme-toggle';
import './js/header';
import './js/render-support';
import './js/firebase-auth';
import './js/modal-auth';
import './js/onRemoveClick';
import './js/tui-pagination';
import './js/modal-team';
import './js/window-resize';
